export const EndPoints = {
  BASEURL: "http://admin.letzparty.lu",
  IMAGE_BASEURL: "http://admin.letzparty.lu/uploads/",
  Login: "/api/login_api",
  Register: "/api/signup_api",
  reset_password_api: "/api/reset_password_api",
  getUserProfile: "/api/get_user_profile",
  getCategory: "/api/get_category",
  get_sub_category: "/api/get_sub_category",
  enquiry_submit: "/api/enquiry_submit",
  get_venue_feature: "/api/get_venue_feature",
  get_entertainment_feature: "/api/get_entertainment_feature",
  add_edit_rental_and_service: "/api/add_edit_rental_and_service",
  event_category: "/api/get_event_category",
  add_edit_venue: "/api/add_edit_venue",
  add_edit_entertainment: "/api/add_edit_entertainment",
  update_user_profile: "/api/update_user_profile",
  change_password_api: "/api/change_password_api",
  logout: "/api/logout",
  get_venue_list_with_filter: "/api/get_venue_list_with_filter",
  get_rental_services_list: "/api/get_rental_and_services_list_with_filter",
  get_property_category_wise: "/api/get_property_category_wise",
  getBookmarks: "/api/get_bookmark_property",
  add_to_bookmark: "/api/add_to_bookmark",
  get_property_detail: "/api/get_property_detail",
  get_entertainment_list_with_filter: "/api/get_entertainment_list_with_filter",
  delete_property: "/api/delete_property",
  get_rental_and_services_list_with_filter:
    "/api/get_rental_and_services_list_with_filter",
  venue_max_filter_data: "/api/venue_max_filter_data",
  get_page_detail: "/api/get_page_detail",
  get_blog_list:"/api/get_blog_list",
  password_verify_api :"/api/password_verify_api",
  switchAnnouncementType:"/api/set_premium",
  updatePassword:'/api/update_password_api'
};
